### ISSUE TITLE
Load all compiled JSON results in Error

### ISSUE THREAD

**Issue by Aniket6990** [7finney/ethcode#275]
whenever I'm hitting the command `load all compiled JSON output` and if no smart contract artifact is present in my working directory then Ethcode results in this error
![image](https://user-images.githubusercontent.com/87822922/210194193-93a7bd03-0ed1-4d7a-b8b0-4057eb453ffc.png)

**Comment by Krish-bhardwaj** [comment]
Missing error handling
1. if contract not compiled error window pops up  
![image](https://user-images.githubusercontent.com/72294477/224013474-abd319cc-f736-464d-9218-89442e7b80c3.png)

2. If we delete the contract and its compiled output it still shows up in the dropdown and API
![image](https://user-images.githubusercontent.com/72294477/224013196-d449f29d-c0ce-4008-9985-1f553699e2d4.png)
